---
title: "Data Analysis on Election Data from Spain"
author: "Seeam S. Noor"
date: "March 14, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(plotly)

x <- read_csv("https://pollofpolls.eu/get/polls/ES-parliament/format/csv")
```

```{r polling, echo = FALSE, warning = FALSE}
# Make a list of firms with at least 40 polls
good_firms <- x %>% 
  group_by(firm) %>% 
  summarize(number = n()) %>% 
  ungroup() %>% 
  filter(number >= 40) %>% 
  pull(firm)
  
# Plotting party percentage support with data taken from only good firms
x %>% 
  filter(firm %in% good_firms) %>% 
  filter(date > Sys.Date() - 365) %>%
  select(-c(source, sd)) %>%
  gather(key = party, value = value, PP, PSOE, Cs, VOX, Podemos) %>%
  ggplot(aes(x = date, y = value, color = party)) +
  geom_point() + 
  geom_smooth(se = FALSE, method = "loess", na.rm = TRUE) +
  labs(x = NULL, y = "Percentage Support", title = "Polling in Advance of Spanish Election on April 28",
       subtitle = "Popular support for VOX surges over last year", caption = "Data source: Poll of polls")
  
```
  
  
## Interactive Plot  

```{r polling2, echo = FALSE, warning = FALSE}

data <-
  x %>%
  filter(firm %in% good_firms) %>%
  filter(date > Sys.Date() - 365) %>%
  select(-c(source, sd)) %>%
  gather(key = party, value = value, PP, PSOE, Cs, VOX, Podemos) %>%
  group_by(date, party) %>%
  summarize(avg_poll = mean(value)) %>%
  spread(key = party, value = avg_poll) %>%
  ungroup()

# Using ployly for interactive plots
plot <- plot_ly(data, x = ~date, y = ~PP, name = 'PP', type = 'scatter', mode = 'lines+markers') %>%
  # Adding traces for diferent parties
  add_trace(y = ~PSOE, name = 'PSOE', mode = 'lines+markers') %>%
  add_trace(y = ~Cs, name = 'CS', mode = 'lines+markers') %>%
  add_trace(y = ~VOX, name = 'VOX', mode = 'lines+markers') %>%
  add_trace(y = ~Podemos, name = 'PODEMOS', mode = 'lines+markers') %>%
  layout(title = "1 Year Election Polls, Spain",
         yaxis = list(title = "Percentage Support"),
         xaxis = list(title = "Date"))


plot

```